// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_identities.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (user_id, provider, provider_subject)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_subject, created_at
`

type CreateAuthIdentityParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ProviderSubject string    `json:"provider_subject"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity, arg.UserID, arg.Provider, arg.ProviderSubject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthIdentityUserID = `-- name: GetAuthIdentityUserID :one
SELECT user_id
FROM auth_identities
WHERE provider = $1
  AND provider_subject = $2
LIMIT 1
`

type GetAuthIdentityUserIDParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetAuthIdentityUserID(ctx context.Context, arg GetAuthIdentityUserIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityUserID, arg.Provider, arg.ProviderSubject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
