// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getLeaderboardXPMetrics = `-- name: GetLeaderboardXPMetrics :many
SELECT u.id AS user_id, COALESCE(up.total_xp, 0)::bigint AS total_xp
FROM users u LEFT JOIN user_progress up ON up.user_id = u.id
WHERE u.deleted_at IS NULL AND u.leaderboard_opt_in = true AND u.shadow_banned = false
`

type GetLeaderboardXPMetricsRow struct {
	UserID  uuid.UUID `json:"user_id"`
	TotalXp int64     `json:"total_xp"`
}

func (q *Queries) GetLeaderboardXPMetrics(ctx context.Context) ([]GetLeaderboardXPMetricsRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardXPMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardXPMetricsRow{}
	for rows.Next() {
		var i GetLeaderboardXPMetricsRow
		if err := rows.Scan(&i.UserID, &i.TotalXp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, name, avatar_seed
FROM users
WHERE id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND leaderboard_opt_in = true
  AND shadow_banned = false
`

type GetUsersByIDsRow struct {
	ID         uuid.UUID `json:"id"`
	Username   string    `json:"username"`
	Name       *string   `json:"name"`
	AvatarSeed string    `json:"avatar_seed"`
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByIDsRow{}
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.AvatarSeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
