// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ProviderSubject string    `json:"provider_subject"`
	CreatedAt       time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	DeviceID   string             `json:"device_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  time.Time          `json:"created_at"`
}

type SafetyAcknowledgement struct {
	UserID         uuid.UUID `json:"user_id"`
	TechniqueID    string    `json:"technique_id"`
	AcknowledgedAt time.Time `json:"acknowledged_at"`
}

type Session struct {
	ID                        uuid.UUID `json:"id"`
	UserID                    uuid.UUID `json:"user_id"`
	ClientSessionID           uuid.UUID `json:"client_session_id"`
	TechniqueID               string    `json:"technique_id"`
	PresetID                  string    `json:"preset_id"`
	StartedAtUtc              time.Time `json:"started_at_utc"`
	EndedAtUtc                time.Time `json:"ended_at_utc"`
	TimezoneOffsetMinutes     int32     `json:"timezone_offset_minutes"`
	LocalDay                  time.Time `json:"local_day"`
	DurationSecondsActual     int32     `json:"duration_seconds_actual"`
	BreathsCompletedEstimated int32     `json:"breaths_completed_estimated"`
	EndedEarly                bool      `json:"ended_early"`
	CreatedAt                 time.Time `json:"created_at"`
}

type StatsSnapshot struct {
	UserID             uuid.UUID `json:"user_id"`
	CurrentStreakDays  int32     `json:"current_streak_days"`
	LongestStreakDays  int32     `json:"longest_streak_days"`
	MinutesThisWeek    int32     `json:"minutes_this_week"`
	MinutesAllTime     int32     `json:"minutes_all_time"`
	SessionsAllTime    int32     `json:"sessions_all_time"`
	MinutesByTechnique []byte    `json:"minutes_by_technique"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type User struct {
	ID                          uuid.UUID          `json:"id"`
	DisplayName                 string             `json:"display_name"`
	AvatarSeed                  string             `json:"avatar_seed"`
	LeaderboardOptIn            bool               `json:"leaderboard_opt_in"`
	LeaderboardInitialsOnly     bool               `json:"leaderboard_initials_only"`
	ShadowBanned                bool               `json:"shadow_banned"`
	AgeBand                     string             `json:"age_band"`
	TimezoneOffsetMinutesLatest int32              `json:"timezone_offset_minutes_latest"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                   time.Time          `json:"created_at"`
}
