// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ProviderSubject string    `json:"provider_subject"`
	CreatedAt       time.Time `json:"created_at"`
}

type EventLog struct {
	ID        int64       `json:"id"`
	Timestamp time.Time   `json:"timestamp"`
	Level     string      `json:"level"`
	EventType string      `json:"event_type"`
	Message   string      `json:"message"`
	RequestID string      `json:"request_id"`
	UserID    pgtype.UUID `json:"user_id"`
	IpAddress string      `json:"ip_address"`
	Provider  string      `json:"provider"`
	Metadata  []byte      `json:"metadata"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	DeviceID   string             `json:"device_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  time.Time          `json:"created_at"`
}

type RequestLog struct {
	ID         int64       `json:"id"`
	Timestamp  time.Time   `json:"timestamp"`
	Method     string      `json:"method"`
	Path       string      `json:"path"`
	StatusCode int32       `json:"status_code"`
	DurationMs float64     `json:"duration_ms"`
	IpAddress  string      `json:"ip_address"`
	UserAgent  string      `json:"user_agent"`
	RequestID  string      `json:"request_id"`
	UserID     pgtype.UUID `json:"user_id"`
	ErrorCode  string      `json:"error_code"`
	ErrorMsg   string      `json:"error_msg"`
}

type SafetyAcknowledgement struct {
	UserID         uuid.UUID `json:"user_id"`
	TechniqueID    string    `json:"technique_id"`
	AcknowledgedAt time.Time `json:"acknowledged_at"`
}

type Session struct {
	ID                        uuid.UUID `json:"id"`
	UserID                    uuid.UUID `json:"user_id"`
	ClientSessionID           uuid.UUID `json:"client_session_id"`
	TechniqueID               string    `json:"technique_id"`
	PresetID                  string    `json:"preset_id"`
	StartedAtUtc              time.Time `json:"started_at_utc"`
	EndedAtUtc                time.Time `json:"ended_at_utc"`
	TimezoneOffsetMinutes     int32     `json:"timezone_offset_minutes"`
	LocalDay                  time.Time `json:"local_day"`
	DurationSecondsActual     int32     `json:"duration_seconds_actual"`
	BreathsCompletedEstimated int32     `json:"breaths_completed_estimated"`
	EndedEarly                bool      `json:"ended_early"`
	CreatedAt                 time.Time `json:"created_at"`
}

type StatsSnapshot struct {
	UserID              uuid.UUID `json:"user_id"`
	CurrentStreakDays   int32     `json:"current_streak_days"`
	LongestStreakDays   int32     `json:"longest_streak_days"`
	MinutesThisWeek     int32     `json:"minutes_this_week"`
	MinutesAllTime      int32     `json:"minutes_all_time"`
	SessionsAllTime     int32     `json:"sessions_all_time"`
	MinutesByTechnique  []byte    `json:"minutes_by_technique"`
	UpdatedAt           time.Time `json:"updated_at"`
	PracticeDaysAllTime int32     `json:"practice_days_all_time"`
}

type User struct {
	ID                          uuid.UUID          `json:"id"`
	DisplayName                 string             `json:"display_name"`
	AvatarSeed                  string             `json:"avatar_seed"`
	LeaderboardOptIn            bool               `json:"leaderboard_opt_in"`
	LeaderboardInitialsOnly     bool               `json:"leaderboard_initials_only"`
	ShadowBanned                bool               `json:"shadow_banned"`
	AgeBand                     string             `json:"age_band"`
	TimezoneOffsetMinutesLatest int32              `json:"timezone_offset_minutes_latest"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                   time.Time          `json:"created_at"`
}

type UserProgress struct {
	UserID       uuid.UUID `json:"user_id"`
	TotalXp      int64     `json:"total_xp"`
	CurrentLevel int32     `json:"current_level"`
	CurveVersion int32     `json:"curve_version"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type XpEvent struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Source       string         `json:"source"`
	Amount       int32          `json:"amount"`
	Multiplier   pgtype.Numeric `json:"multiplier"`
	BaseAmount   int32          `json:"base_amount"`
	SessionID    pgtype.UUID    `json:"session_id"`
	LocalDay     time.Time      `json:"local_day"`
	CurveVersion int32          `json:"curve_version"`
	CreatedAt    time.Time      `json:"created_at"`
}
