// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_installations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindInstallationToUser = `-- name: BindInstallationToUser :exec
UPDATE notification_installations SET user_id = $2, updated_at = now() WHERE device_id = $1
`

type BindInstallationToUserParams struct {
	DeviceID string      `json:"device_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) BindInstallationToUser(ctx context.Context, arg BindInstallationToUserParams) error {
	_, err := q.db.Exec(ctx, bindInstallationToUser, arg.DeviceID, arg.UserID)
	return err
}

const deleteInstallationByDeviceID = `-- name: DeleteInstallationByDeviceID :exec
DELETE FROM notification_installations WHERE device_id = $1
`

func (q *Queries) DeleteInstallationByDeviceID(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, deleteInstallationByDeviceID, deviceID)
	return err
}

const deleteInstallationByFCMToken = `-- name: DeleteInstallationByFCMToken :exec
DELETE FROM notification_installations WHERE fcm_token = $1
`

func (q *Queries) DeleteInstallationByFCMToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteInstallationByFCMToken, fcmToken)
	return err
}

const getDueDailyReminders = `-- name: GetDueDailyReminders :many
SELECT device_id, fcm_token, platform
FROM notification_installations
WHERE reminder_enabled = true
  AND permission_status = 'authorized'
  AND reminder_time_minutes = $1
  AND timezone_iana = $2
  AND (last_daily_sent_local_day IS NULL OR last_daily_sent_local_day < $3::date)
  AND (user_id IS NULL OR EXISTS (
    SELECT 1 FROM users u WHERE u.id = notification_installations.user_id AND u.deleted_at IS NULL
  ))
`

type GetDueDailyRemindersParams struct {
	ReminderTimeMinutes int32     `json:"reminder_time_minutes"`
	TimezoneIana        string    `json:"timezone_iana"`
	Column3             time.Time `json:"column_3"`
}

type GetDueDailyRemindersRow struct {
	DeviceID string `json:"device_id"`
	FcmToken string `json:"fcm_token"`
	Platform string `json:"platform"`
}

func (q *Queries) GetDueDailyReminders(ctx context.Context, arg GetDueDailyRemindersParams) ([]GetDueDailyRemindersRow, error) {
	rows, err := q.db.Query(ctx, getDueDailyReminders, arg.ReminderTimeMinutes, arg.TimezoneIana, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDueDailyRemindersRow{}
	for rows.Next() {
		var i GetDueDailyRemindersRow
		if err := rows.Scan(&i.DeviceID, &i.FcmToken, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueStreakWarnings = `-- name: GetDueStreakWarnings :many
SELECT ni.device_id, ni.fcm_token, ni.platform
FROM notification_installations ni
JOIN users u ON u.id = ni.user_id AND u.deleted_at IS NULL
JOIN stats_snapshots ss ON ss.user_id = ni.user_id
WHERE ni.streak_warning_enabled = true
  AND ni.permission_status = 'authorized'
  AND ss.current_streak_days > 0
  AND ni.timezone_iana = $1
  AND (ni.last_streak_sent_local_day IS NULL OR ni.last_streak_sent_local_day < $2::date)
  AND NOT EXISTS (
    SELECT 1 FROM sessions s
    WHERE s.user_id = ni.user_id
      AND s.started_at_utc >= ($2::date - make_interval(secs => ni.timezone_offset_minutes * 60))
      AND s.started_at_utc < ($2::date + interval '1 day' - make_interval(secs => ni.timezone_offset_minutes * 60))
      AND s.duration_seconds_actual >= 120
  )
`

type GetDueStreakWarningsParams struct {
	TimezoneIana string    `json:"timezone_iana"`
	Column2      time.Time `json:"column_2"`
}

type GetDueStreakWarningsRow struct {
	DeviceID string `json:"device_id"`
	FcmToken string `json:"fcm_token"`
	Platform string `json:"platform"`
}

func (q *Queries) GetDueStreakWarnings(ctx context.Context, arg GetDueStreakWarningsParams) ([]GetDueStreakWarningsRow, error) {
	rows, err := q.db.Query(ctx, getDueStreakWarnings, arg.TimezoneIana, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDueStreakWarningsRow{}
	for rows.Next() {
		var i GetDueStreakWarningsRow
		if err := rows.Scan(&i.DeviceID, &i.FcmToken, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstallationByDeviceID = `-- name: GetInstallationByDeviceID :one
SELECT device_id, user_id, platform, fcm_token, permission_status, reminder_enabled, reminder_time_minutes, streak_warning_enabled, timezone_iana, timezone_offset_minutes, app_version, build_number, locale, last_seen_at, last_daily_sent_local_day, last_streak_sent_local_day, last_send_error, created_at, updated_at FROM notification_installations WHERE device_id = $1
`

func (q *Queries) GetInstallationByDeviceID(ctx context.Context, deviceID string) (NotificationInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByDeviceID, deviceID)
	var i NotificationInstallation
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.Platform,
		&i.FcmToken,
		&i.PermissionStatus,
		&i.ReminderEnabled,
		&i.ReminderTimeMinutes,
		&i.StreakWarningEnabled,
		&i.TimezoneIana,
		&i.TimezoneOffsetMinutes,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.LastSeenAt,
		&i.LastDailySentLocalDay,
		&i.LastStreakSentLocalDay,
		&i.LastSendError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationsByUserID = `-- name: GetInstallationsByUserID :many
SELECT device_id, user_id, platform, fcm_token, permission_status, reminder_enabled, reminder_time_minutes, streak_warning_enabled, timezone_iana, timezone_offset_minutes, app_version, build_number, locale, last_seen_at, last_daily_sent_local_day, last_streak_sent_local_day, last_send_error, created_at, updated_at FROM notification_installations WHERE user_id = $1
`

func (q *Queries) GetInstallationsByUserID(ctx context.Context, userID pgtype.UUID) ([]NotificationInstallation, error) {
	rows, err := q.db.Query(ctx, getInstallationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationInstallation{}
	for rows.Next() {
		var i NotificationInstallation
		if err := rows.Scan(
			&i.DeviceID,
			&i.UserID,
			&i.Platform,
			&i.FcmToken,
			&i.PermissionStatus,
			&i.ReminderEnabled,
			&i.ReminderTimeMinutes,
			&i.StreakWarningEnabled,
			&i.TimezoneIana,
			&i.TimezoneOffsetMinutes,
			&i.AppVersion,
			&i.BuildNumber,
			&i.Locale,
			&i.LastSeenAt,
			&i.LastDailySentLocalDay,
			&i.LastStreakSentLocalDay,
			&i.LastSendError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctActiveTimezones = `-- name: ListDistinctActiveTimezones :many
SELECT DISTINCT timezone_iana FROM notification_installations WHERE reminder_enabled = true
`

func (q *Queries) ListDistinctActiveTimezones(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctActiveTimezones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var timezone_iana string
		if err := rows.Scan(&timezone_iana); err != nil {
			return nil, err
		}
		items = append(items, timezone_iana)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctStreakTimezones = `-- name: ListDistinctStreakTimezones :many
SELECT DISTINCT timezone_iana FROM notification_installations
WHERE streak_warning_enabled = true AND user_id IS NOT NULL
`

func (q *Queries) ListDistinctStreakTimezones(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctStreakTimezones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var timezone_iana string
		if err := rows.Scan(&timezone_iana); err != nil {
			return nil, err
		}
		items = append(items, timezone_iana)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailyReminderSent = `-- name: MarkDailyReminderSent :exec
UPDATE notification_installations
SET last_daily_sent_local_day = $2, last_send_error = NULL, updated_at = now()
WHERE device_id = $1
`

type MarkDailyReminderSentParams struct {
	DeviceID              string      `json:"device_id"`
	LastDailySentLocalDay pgtype.Date `json:"last_daily_sent_local_day"`
}

func (q *Queries) MarkDailyReminderSent(ctx context.Context, arg MarkDailyReminderSentParams) error {
	_, err := q.db.Exec(ctx, markDailyReminderSent, arg.DeviceID, arg.LastDailySentLocalDay)
	return err
}

const markSendError = `-- name: MarkSendError :exec
UPDATE notification_installations
SET last_send_error = $2, updated_at = now()
WHERE device_id = $1
`

type MarkSendErrorParams struct {
	DeviceID      string  `json:"device_id"`
	LastSendError *string `json:"last_send_error"`
}

func (q *Queries) MarkSendError(ctx context.Context, arg MarkSendErrorParams) error {
	_, err := q.db.Exec(ctx, markSendError, arg.DeviceID, arg.LastSendError)
	return err
}

const markStreakWarningSent = `-- name: MarkStreakWarningSent :exec
UPDATE notification_installations
SET last_streak_sent_local_day = $2, last_send_error = NULL, updated_at = now()
WHERE device_id = $1
`

type MarkStreakWarningSentParams struct {
	DeviceID               string      `json:"device_id"`
	LastStreakSentLocalDay pgtype.Date `json:"last_streak_sent_local_day"`
}

func (q *Queries) MarkStreakWarningSent(ctx context.Context, arg MarkStreakWarningSentParams) error {
	_, err := q.db.Exec(ctx, markStreakWarningSent, arg.DeviceID, arg.LastStreakSentLocalDay)
	return err
}

const unbindInstallation = `-- name: UnbindInstallation :exec
UPDATE notification_installations
SET user_id = NULL, last_streak_sent_local_day = NULL, updated_at = now()
WHERE device_id = $1 AND user_id = $2
`

type UnbindInstallationParams struct {
	DeviceID string      `json:"device_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnbindInstallation(ctx context.Context, arg UnbindInstallationParams) error {
	_, err := q.db.Exec(ctx, unbindInstallation, arg.DeviceID, arg.UserID)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :one
INSERT INTO notification_installations (
  device_id, user_id, platform, fcm_token, permission_status,
  reminder_enabled, reminder_time_minutes, streak_warning_enabled,
  timezone_iana, timezone_offset_minutes, app_version, build_number, locale,
  last_seen_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now(), now())
ON CONFLICT (device_id) DO UPDATE SET
  user_id = COALESCE(EXCLUDED.user_id, notification_installations.user_id),
  platform = EXCLUDED.platform,
  fcm_token = EXCLUDED.fcm_token,
  permission_status = EXCLUDED.permission_status,
  reminder_enabled = EXCLUDED.reminder_enabled,
  reminder_time_minutes = EXCLUDED.reminder_time_minutes,
  streak_warning_enabled = EXCLUDED.streak_warning_enabled,
  timezone_iana = EXCLUDED.timezone_iana,
  timezone_offset_minutes = EXCLUDED.timezone_offset_minutes,
  app_version = EXCLUDED.app_version,
  build_number = EXCLUDED.build_number,
  locale = EXCLUDED.locale,
  last_seen_at = now(),
  updated_at = now()
RETURNING device_id, user_id, platform, fcm_token, permission_status, reminder_enabled, reminder_time_minutes, streak_warning_enabled, timezone_iana, timezone_offset_minutes, app_version, build_number, locale, last_seen_at, last_daily_sent_local_day, last_streak_sent_local_day, last_send_error, created_at, updated_at
`

type UpsertInstallationParams struct {
	DeviceID              string      `json:"device_id"`
	UserID                pgtype.UUID `json:"user_id"`
	Platform              string      `json:"platform"`
	FcmToken              string      `json:"fcm_token"`
	PermissionStatus      string      `json:"permission_status"`
	ReminderEnabled       bool        `json:"reminder_enabled"`
	ReminderTimeMinutes   int32       `json:"reminder_time_minutes"`
	StreakWarningEnabled  bool        `json:"streak_warning_enabled"`
	TimezoneIana          string      `json:"timezone_iana"`
	TimezoneOffsetMinutes int32       `json:"timezone_offset_minutes"`
	AppVersion            string      `json:"app_version"`
	BuildNumber           string      `json:"build_number"`
	Locale                string      `json:"locale"`
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (NotificationInstallation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.DeviceID,
		arg.UserID,
		arg.Platform,
		arg.FcmToken,
		arg.PermissionStatus,
		arg.ReminderEnabled,
		arg.ReminderTimeMinutes,
		arg.StreakWarningEnabled,
		arg.TimezoneIana,
		arg.TimezoneOffsetMinutes,
		arg.AppVersion,
		arg.BuildNumber,
		arg.Locale,
	)
	var i NotificationInstallation
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.Platform,
		&i.FcmToken,
		&i.PermissionStatus,
		&i.ReminderEnabled,
		&i.ReminderTimeMinutes,
		&i.StreakWarningEnabled,
		&i.TimezoneIana,
		&i.TimezoneOffsetMinutes,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.LastSeenAt,
		&i.LastDailySentLocalDay,
		&i.LastStreakSentLocalDay,
		&i.LastSendError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
