// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: safety_acknowledgements.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addSafetyAcknowledgement = `-- name: AddSafetyAcknowledgement :exec
INSERT INTO safety_acknowledgements (user_id, technique_id)
VALUES ($1, $2)
ON CONFLICT (user_id, technique_id) DO NOTHING
`

type AddSafetyAcknowledgementParams struct {
	UserID      uuid.UUID `json:"user_id"`
	TechniqueID string    `json:"technique_id"`
}

func (q *Queries) AddSafetyAcknowledgement(ctx context.Context, arg AddSafetyAcknowledgementParams) error {
	_, err := q.db.Exec(ctx, addSafetyAcknowledgement, arg.UserID, arg.TechniqueID)
	return err
}

const deleteSafetyAcknowledgementsByUserID = `-- name: DeleteSafetyAcknowledgementsByUserID :exec
DELETE FROM safety_acknowledgements
WHERE user_id = $1
`

func (q *Queries) DeleteSafetyAcknowledgementsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSafetyAcknowledgementsByUserID, userID)
	return err
}

const listSafetyAcknowledgementsByUserID = `-- name: ListSafetyAcknowledgementsByUserID :many
SELECT technique_id
FROM safety_acknowledgements
WHERE user_id = $1
ORDER BY technique_id
`

func (q *Queries) ListSafetyAcknowledgementsByUserID(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSafetyAcknowledgementsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var technique_id string
		if err := rows.Scan(&technique_id); err != nil {
			return nil, err
		}
		items = append(items, technique_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
