// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSessionByClientID = `-- name: GetSessionByClientID :one
SELECT id, duration_seconds_actual, ended_early, local_day FROM sessions WHERE client_session_id = $1
`

type GetSessionByClientIDRow struct {
	ID                    uuid.UUID `json:"id"`
	DurationSecondsActual int32     `json:"duration_seconds_actual"`
	EndedEarly            bool      `json:"ended_early"`
	LocalDay              time.Time `json:"local_day"`
}

func (q *Queries) GetSessionByClientID(ctx context.Context, clientSessionID uuid.UUID) (GetSessionByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByClientID, clientSessionID)
	var i GetSessionByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.DurationSecondsActual,
		&i.EndedEarly,
		&i.LocalDay,
	)
	return i, err
}

const getSessionCount = `-- name: GetSessionCount :one
SELECT COUNT(*)::bigint AS session_count
FROM sessions
WHERE user_id = $1
`

func (q *Queries) GetSessionCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionCount, userID)
	var session_count int64
	err := row.Scan(&session_count)
	return session_count, err
}

const getSessionDayTotals = `-- name: GetSessionDayTotals :many
SELECT local_day, COALESCE(SUM(duration_seconds_actual), 0)::bigint AS total_seconds
FROM sessions
WHERE user_id = $1
GROUP BY local_day
ORDER BY local_day
`

type GetSessionDayTotalsRow struct {
	LocalDay     time.Time `json:"local_day"`
	TotalSeconds int64     `json:"total_seconds"`
}

func (q *Queries) GetSessionDayTotals(ctx context.Context, userID uuid.UUID) ([]GetSessionDayTotalsRow, error) {
	rows, err := q.db.Query(ctx, getSessionDayTotals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionDayTotalsRow{}
	for rows.Next() {
		var i GetSessionDayTotalsRow
		if err := rows.Scan(&i.LocalDay, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionSecondsInRange = `-- name: GetSessionSecondsInRange :one
SELECT COALESCE(SUM(duration_seconds_actual), 0)::bigint AS total_seconds
FROM sessions
WHERE user_id = $1
  AND local_day >= $2
  AND local_day < $3
`

type GetSessionSecondsInRangeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	LocalDay   time.Time `json:"local_day"`
	LocalDay_2 time.Time `json:"local_day_2"`
}

func (q *Queries) GetSessionSecondsInRange(ctx context.Context, arg GetSessionSecondsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionSecondsInRange, arg.UserID, arg.LocalDay, arg.LocalDay_2)
	var total_seconds int64
	err := row.Scan(&total_seconds)
	return total_seconds, err
}

const getTechniqueTotals = `-- name: GetTechniqueTotals :many
SELECT technique_id, COALESCE(SUM(duration_seconds_actual), 0)::bigint AS total_seconds
FROM sessions
WHERE user_id = $1
GROUP BY technique_id
`

type GetTechniqueTotalsRow struct {
	TechniqueID  string `json:"technique_id"`
	TotalSeconds int64  `json:"total_seconds"`
}

func (q *Queries) GetTechniqueTotals(ctx context.Context, userID uuid.UUID) ([]GetTechniqueTotalsRow, error) {
	rows, err := q.db.Query(ctx, getTechniqueTotals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTechniqueTotalsRow{}
	for rows.Next() {
		var i GetTechniqueTotalsRow
		if err := rows.Scan(&i.TechniqueID, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSessionSeconds = `-- name: GetTotalSessionSeconds :one
SELECT COALESCE(SUM(duration_seconds_actual), 0)::bigint AS total_seconds
FROM sessions
WHERE user_id = $1
`

func (q *Queries) GetTotalSessionSeconds(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalSessionSeconds, userID)
	var total_seconds int64
	err := row.Scan(&total_seconds)
	return total_seconds, err
}

const insertSession = `-- name: InsertSession :execrows
INSERT INTO sessions (
  user_id,
  client_session_id,
  technique_id,
  preset_id,
  started_at_utc,
  ended_at_utc,
  timezone_offset_minutes,
  local_day,
  duration_seconds_actual,
  breaths_completed_estimated,
  ended_early
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (client_session_id) DO NOTHING
`

type InsertSessionParams struct {
	UserID                    uuid.UUID `json:"user_id"`
	ClientSessionID           uuid.UUID `json:"client_session_id"`
	TechniqueID               string    `json:"technique_id"`
	PresetID                  string    `json:"preset_id"`
	StartedAtUtc              time.Time `json:"started_at_utc"`
	EndedAtUtc                time.Time `json:"ended_at_utc"`
	TimezoneOffsetMinutes     int32     `json:"timezone_offset_minutes"`
	LocalDay                  time.Time `json:"local_day"`
	DurationSecondsActual     int32     `json:"duration_seconds_actual"`
	BreathsCompletedEstimated int32     `json:"breaths_completed_estimated"`
	EndedEarly                bool      `json:"ended_early"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSession,
		arg.UserID,
		arg.ClientSessionID,
		arg.TechniqueID,
		arg.PresetID,
		arg.StartedAtUtc,
		arg.EndedAtUtc,
		arg.TimezoneOffsetMinutes,
		arg.LocalDay,
		arg.DurationSecondsActual,
		arg.BreathsCompletedEstimated,
		arg.EndedEarly,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
