// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getStatsSnapshot = `-- name: GetStatsSnapshot :one
SELECT user_id, current_streak_days, longest_streak_days, minutes_this_week, minutes_all_time, sessions_all_time, minutes_by_technique, updated_at
FROM stats_snapshots
WHERE user_id = $1
`

func (q *Queries) GetStatsSnapshot(ctx context.Context, userID uuid.UUID) (StatsSnapshot, error) {
	row := q.db.QueryRow(ctx, getStatsSnapshot, userID)
	var i StatsSnapshot
	err := row.Scan(
		&i.UserID,
		&i.CurrentStreakDays,
		&i.LongestStreakDays,
		&i.MinutesThisWeek,
		&i.MinutesAllTime,
		&i.SessionsAllTime,
		&i.MinutesByTechnique,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStatsSnapshot = `-- name: UpsertStatsSnapshot :one
INSERT INTO stats_snapshots (
  user_id,
  current_streak_days,
  longest_streak_days,
  minutes_this_week,
  minutes_all_time,
  sessions_all_time,
  minutes_by_technique,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (user_id)
DO UPDATE SET
  current_streak_days = EXCLUDED.current_streak_days,
  longest_streak_days = EXCLUDED.longest_streak_days,
  minutes_this_week = EXCLUDED.minutes_this_week,
  minutes_all_time = EXCLUDED.minutes_all_time,
  sessions_all_time = EXCLUDED.sessions_all_time,
  minutes_by_technique = EXCLUDED.minutes_by_technique,
  updated_at = now()
RETURNING user_id, current_streak_days, longest_streak_days, minutes_this_week, minutes_all_time, sessions_all_time, minutes_by_technique, updated_at
`

type UpsertStatsSnapshotParams struct {
	UserID             uuid.UUID `json:"user_id"`
	CurrentStreakDays  int32     `json:"current_streak_days"`
	LongestStreakDays  int32     `json:"longest_streak_days"`
	MinutesThisWeek    int32     `json:"minutes_this_week"`
	MinutesAllTime     int32     `json:"minutes_all_time"`
	SessionsAllTime    int32     `json:"sessions_all_time"`
	MinutesByTechnique []byte    `json:"minutes_by_technique"`
}

func (q *Queries) UpsertStatsSnapshot(ctx context.Context, arg UpsertStatsSnapshotParams) (StatsSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertStatsSnapshot,
		arg.UserID,
		arg.CurrentStreakDays,
		arg.LongestStreakDays,
		arg.MinutesThisWeek,
		arg.MinutesAllTime,
		arg.SessionsAllTime,
		arg.MinutesByTechnique,
	)
	var i StatsSnapshot
	err := row.Scan(
		&i.UserID,
		&i.CurrentStreakDays,
		&i.LongestStreakDays,
		&i.MinutesThisWeek,
		&i.MinutesAllTime,
		&i.SessionsAllTime,
		&i.MinutesByTechnique,
		&i.UpdatedAt,
	)
	return i, err
}
