// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE lower(username) = lower($1) AND deleted_at IS NULL)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, avatar_seed, age_band, timezone_offset_minutes_latest)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
`

type CreateUserParams struct {
	Username                    string  `json:"username"`
	Name                        *string `json:"name"`
	AvatarSeed                  string  `json:"avatar_seed"`
	AgeBand                     string  `json:"age_band"`
	TimezoneOffsetMinutesLatest int32   `json:"timezone_offset_minutes_latest"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.AvatarSeed,
		arg.AgeBand,
		arg.TimezoneOffsetMinutesLatest,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const deleteAuthIdentitiesByUserID = `-- name: DeleteAuthIdentitiesByUserID :exec
DELETE FROM auth_identities
WHERE user_id = $1
`

func (q *Queries) DeleteAuthIdentitiesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthIdentitiesByUserID, userID)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteStatsSnapshotByUserID = `-- name: DeleteStatsSnapshotByUserID :exec
DELETE FROM stats_snapshots
WHERE user_id = $1
`

func (q *Queries) DeleteStatsSnapshotByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStatsSnapshotByUserID, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
FROM users
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const getUserByIDAllowDeleted = `-- name: GetUserByIDAllowDeleted :one
SELECT id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByIDAllowDeleted(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDAllowDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const markUserDeleted = `-- name: MarkUserDeleted :one
UPDATE users
SET deleted_at = now(),
    leaderboard_opt_in = false,
    username = $2,
    avatar_seed = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
`

type MarkUserDeletedParams struct {
	ID         uuid.UUID `json:"id"`
	Username   string    `json:"username"`
	AvatarSeed string    `json:"avatar_seed"`
}

func (q *Queries) MarkUserDeleted(ctx context.Context, arg MarkUserDeletedParams) (User, error) {
	row := q.db.QueryRow(ctx, markUserDeleted, arg.ID, arg.Username, arg.AvatarSeed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const updateUserLeaderboardPrefs = `-- name: UpdateUserLeaderboardPrefs :one
UPDATE users
SET leaderboard_opt_in = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
`

type UpdateUserLeaderboardPrefsParams struct {
	ID               uuid.UUID `json:"id"`
	LeaderboardOptIn bool      `json:"leaderboard_opt_in"`
}

func (q *Queries) UpdateUserLeaderboardPrefs(ctx context.Context, arg UpdateUserLeaderboardPrefsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLeaderboardPrefs, arg.ID, arg.LeaderboardOptIn)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
`

type UpdateUserNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const updateUserTimezoneOffset = `-- name: UpdateUserTimezoneOffset :one
UPDATE users
SET timezone_offset_minutes_latest = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
`

type UpdateUserTimezoneOffsetParams struct {
	ID                          uuid.UUID `json:"id"`
	TimezoneOffsetMinutesLatest int32     `json:"timezone_offset_minutes_latest"`
}

func (q *Queries) UpdateUserTimezoneOffset(ctx context.Context, arg UpdateUserTimezoneOffsetParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTimezoneOffset, arg.ID, arg.TimezoneOffsetMinutesLatest)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users
SET username = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, avatar_seed, leaderboard_opt_in, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at, username, name
`

type UpdateUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
	)
	return i, err
}
