// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name, avatar_seed, age_band, timezone_offset_minutes_latest)
VALUES ($1, $2, $3, $4)
RETURNING id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
`

type CreateUserParams struct {
	DisplayName                 string `json:"display_name"`
	AvatarSeed                  string `json:"avatar_seed"`
	AgeBand                     string `json:"age_band"`
	TimezoneOffsetMinutesLatest int32  `json:"timezone_offset_minutes_latest"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.AvatarSeed,
		arg.AgeBand,
		arg.TimezoneOffsetMinutesLatest,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthIdentitiesByUserID = `-- name: DeleteAuthIdentitiesByUserID :exec
DELETE FROM auth_identities
WHERE user_id = $1
`

func (q *Queries) DeleteAuthIdentitiesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthIdentitiesByUserID, userID)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteStatsSnapshotByUserID = `-- name: DeleteStatsSnapshotByUserID :exec
DELETE FROM stats_snapshots
WHERE user_id = $1
`

func (q *Queries) DeleteStatsSnapshotByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStatsSnapshotByUserID, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIDAllowDeleted = `-- name: GetUserByIDAllowDeleted :one
SELECT id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByIDAllowDeleted(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDAllowDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserDeleted = `-- name: MarkUserDeleted :one
UPDATE users
SET deleted_at = now(),
    leaderboard_opt_in = false,
    leaderboard_initials_only = false,
    display_name = $2,
    avatar_seed = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
`

type MarkUserDeletedParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	AvatarSeed  string    `json:"avatar_seed"`
}

func (q *Queries) MarkUserDeleted(ctx context.Context, arg MarkUserDeletedParams) (User, error) {
	row := q.db.QueryRow(ctx, markUserDeleted, arg.ID, arg.DisplayName, arg.AvatarSeed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserLeaderboardPrefs = `-- name: UpdateUserLeaderboardPrefs :one
UPDATE users
SET leaderboard_opt_in = $2,
    leaderboard_initials_only = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
`

type UpdateUserLeaderboardPrefsParams struct {
	ID                      uuid.UUID `json:"id"`
	LeaderboardOptIn        bool      `json:"leaderboard_opt_in"`
	LeaderboardInitialsOnly bool      `json:"leaderboard_initials_only"`
}

func (q *Queries) UpdateUserLeaderboardPrefs(ctx context.Context, arg UpdateUserLeaderboardPrefsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLeaderboardPrefs, arg.ID, arg.LeaderboardOptIn, arg.LeaderboardInitialsOnly)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserTimezoneOffset = `-- name: UpdateUserTimezoneOffset :one
UPDATE users
SET timezone_offset_minutes_latest = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, display_name, avatar_seed, leaderboard_opt_in, leaderboard_initials_only, shadow_banned, age_band, timezone_offset_minutes_latest, deleted_at, created_at
`

type UpdateUserTimezoneOffsetParams struct {
	ID                          uuid.UUID `json:"id"`
	TimezoneOffsetMinutesLatest int32     `json:"timezone_offset_minutes_latest"`
}

func (q *Queries) UpdateUserTimezoneOffset(ctx context.Context, arg UpdateUserTimezoneOffsetParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTimezoneOffset, arg.ID, arg.TimezoneOffsetMinutesLatest)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarSeed,
		&i.LeaderboardOptIn,
		&i.LeaderboardInitialsOnly,
		&i.ShadowBanned,
		&i.AgeBand,
		&i.TimezoneOffsetMinutesLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
