// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xp.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserProgress = `-- name: DeleteUserProgress :exec
DELETE FROM user_progress WHERE user_id = $1
`

func (q *Queries) DeleteUserProgress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserProgress, userID)
	return err
}

const deleteXPEventsByUser = `-- name: DeleteXPEventsByUser :exec
DELETE FROM xp_events WHERE user_id = $1
`

func (q *Queries) DeleteXPEventsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteXPEventsByUser, userID)
	return err
}

const getDailyPracticeXP = `-- name: GetDailyPracticeXP :one
SELECT COALESCE(SUM(amount), 0)::int AS daily_practice_xp
FROM xp_events
WHERE user_id = $1 AND local_day = $2 AND source = 'session'
`

type GetDailyPracticeXPParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LocalDay time.Time `json:"local_day"`
}

func (q *Queries) GetDailyPracticeXP(ctx context.Context, arg GetDailyPracticeXPParams) (int32, error) {
	row := q.db.QueryRow(ctx, getDailyPracticeXP, arg.UserID, arg.LocalDay)
	var daily_practice_xp int32
	err := row.Scan(&daily_practice_xp)
	return daily_practice_xp, err
}

const getDailyXPHistory = `-- name: GetDailyXPHistory :many
SELECT local_day,
       SUM(amount)::int AS total_xp,
       SUM(CASE WHEN source = 'session' THEN amount ELSE 0 END)::int AS practice_xp,
       SUM(CASE WHEN source = 'daily_open' THEN amount ELSE 0 END)::int AS login_xp
FROM xp_events
WHERE user_id = $1 AND local_day >= $2
GROUP BY local_day
ORDER BY local_day DESC
`

type GetDailyXPHistoryParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LocalDay time.Time `json:"local_day"`
}

type GetDailyXPHistoryRow struct {
	LocalDay   time.Time `json:"local_day"`
	TotalXp    int32     `json:"total_xp"`
	PracticeXp int32     `json:"practice_xp"`
	LoginXp    int32     `json:"login_xp"`
}

func (q *Queries) GetDailyXPHistory(ctx context.Context, arg GetDailyXPHistoryParams) ([]GetDailyXPHistoryRow, error) {
	rows, err := q.db.Query(ctx, getDailyXPHistory, arg.UserID, arg.LocalDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyXPHistoryRow{}
	for rows.Next() {
		var i GetDailyXPHistoryRow
		if err := rows.Scan(
			&i.LocalDay,
			&i.TotalXp,
			&i.PracticeXp,
			&i.LoginXp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalXP = `-- name: GetTotalXP :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total_xp FROM xp_events WHERE user_id = $1
`

func (q *Queries) GetTotalXP(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalXP, userID)
	var total_xp int64
	err := row.Scan(&total_xp)
	return total_xp, err
}

const getUserProgress = `-- name: GetUserProgress :one
SELECT user_id, total_xp, current_level, curve_version, updated_at FROM user_progress WHERE user_id = $1
`

func (q *Queries) GetUserProgress(ctx context.Context, userID uuid.UUID) (UserProgress, error) {
	row := q.db.QueryRow(ctx, getUserProgress, userID)
	var i UserProgress
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.CurrentLevel,
		&i.CurveVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const hasDailyOpenXP = `-- name: HasDailyOpenXP :one
SELECT EXISTS(
  SELECT 1 FROM xp_events WHERE user_id = $1 AND local_day = $2 AND source = 'daily_open'
) AS has_daily_open_xp
`

type HasDailyOpenXPParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LocalDay time.Time `json:"local_day"`
}

func (q *Queries) HasDailyOpenXP(ctx context.Context, arg HasDailyOpenXPParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasDailyOpenXP, arg.UserID, arg.LocalDay)
	var has_daily_open_xp bool
	err := row.Scan(&has_daily_open_xp)
	return has_daily_open_xp, err
}

const insertXPEvent = `-- name: InsertXPEvent :one
INSERT INTO xp_events (user_id, source, amount, multiplier, base_amount, session_id, local_day, curve_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, source, amount, multiplier, base_amount, session_id, local_day, curve_version, created_at
`

type InsertXPEventParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Source       string         `json:"source"`
	Amount       int32          `json:"amount"`
	Multiplier   pgtype.Numeric `json:"multiplier"`
	BaseAmount   int32          `json:"base_amount"`
	SessionID    pgtype.UUID    `json:"session_id"`
	LocalDay     time.Time      `json:"local_day"`
	CurveVersion int32          `json:"curve_version"`
}

func (q *Queries) InsertXPEvent(ctx context.Context, arg InsertXPEventParams) (XpEvent, error) {
	row := q.db.QueryRow(ctx, insertXPEvent,
		arg.UserID,
		arg.Source,
		arg.Amount,
		arg.Multiplier,
		arg.BaseAmount,
		arg.SessionID,
		arg.LocalDay,
		arg.CurveVersion,
	)
	var i XpEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Amount,
		&i.Multiplier,
		&i.BaseAmount,
		&i.SessionID,
		&i.LocalDay,
		&i.CurveVersion,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserProgress = `-- name: UpsertUserProgress :one
INSERT INTO user_progress (user_id, total_xp, current_level, curve_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
  total_xp = $2, current_level = $3, curve_version = $4, updated_at = now()
RETURNING user_id, total_xp, current_level, curve_version, updated_at
`

type UpsertUserProgressParams struct {
	UserID       uuid.UUID `json:"user_id"`
	TotalXp      int64     `json:"total_xp"`
	CurrentLevel int32     `json:"current_level"`
	CurveVersion int32     `json:"curve_version"`
}

func (q *Queries) UpsertUserProgress(ctx context.Context, arg UpsertUserProgressParams) (UserProgress, error) {
	row := q.db.QueryRow(ctx, upsertUserProgress,
		arg.UserID,
		arg.TotalXp,
		arg.CurrentLevel,
		arg.CurveVersion,
	)
	var i UserProgress
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.CurrentLevel,
		&i.CurveVersion,
		&i.UpdatedAt,
	)
	return i, err
}
